= Lee De Zhang - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: BizConnect Journal

---

== Overview

BizConnect Journal is an application catered to busy businessmen who also enjoy traveling to manage their contacts,
events and tasks. It uses Command Line Interface (CLI) as the primary source of input.

Businessmen tend to have a lot of meetings and networking session with new people which include exchanging contacts,
thus the above features will be useful for them as they can access all of them in one application without the trouble
of a separate application for each purpose.

At any point of time, businessman can refer to schedules to keep informed on what is up in the next few hours or
the day later, aiding them to make informed decision. On the other hand, task list comes in handy to update them of
the upcoming tasks and the tasks’ urgency. This helps them to prioritise what should be completed.

Beside that, traveling usually involves the hassle of not knowing exactly the amount of money to change.
Hence, the currency converter aim to facilitate the fast knowledge of the amount to change without having to use
a separate application or an online converter.

A simple day-to-day life of a businessman can be packed with many schedules and having a single place to manage
all their necessary information for work makes it easier and more time can be spent on the actual work.
With all these in mind, BizConnect Journal is developed to ease the management of the busy schedule of businessmen.

<Insert app UI>

== Summary of contributions

* *Major enhancement*: Picture feature to facilitate *networking and contact management*

** *What it does*:
It allows a businessman to add or remove a profile picture for a contact.

** *Justification*:
By default, a contact has a default picture displayed. A user can then choose to display a picture alongside
the contact.

As a businessman is expected to meet a lot of people, chances are that he/she would not be able to recognize someone
by name only. A picture would help with this.

A user is then given the option to remove a picture by resetting it to the default picture again.

** *Highlights*: This enhancement interacts with the system's file storage. Therefore, an in depth study of the related APIs
was required to ensure the functionality of this feature

* *Minor enhancement*: Added a delete by name command. This allows a user to delete a contact by name, other than by index.
* *Minor enhancement*: Added a add tag command. This allows a user to add individual or multiple tags to a contact.

* *Code contributed*: [https://github.com/CS2103JAN2018-T15-B4/main/tree/master/collated/functional/dezhanglee.md[Functional code]] [https://github.com/CS2103JAN2018-T15-B4/main/tree/master/collated/test/dezhanglee.md[Test code]]

* *Other contributions*:
** Documentation:
*** Wrote use cases for implemented features
*** Wrote user stories, project description in Project Portfolio with team

** Community:
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/CS2103JAN2018-T09-B4/main/issues/140, https://github.com/CS2103JAN2018-T09-B4/main/issues/143, https://github.com/CS2103JAN2018-T09-B4/main/issues/153)

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=deletebyname]

include::../UserGuide.adoc[tag=addpicture]

include::../UserGuide.adoc[tag=resetpicture]

include::../UserGuide.adoc[tag=addtag]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=addtag]

include::../DeveloperGuide.adoc[tag=addpicture]

include::../DeveloperGuide.adoc[tag=resetpicture]

include::../DeveloperGuide.adoc[tag=deletebyname]
